# Build settings
gems:
- github-pages
- jekyll-mentions
- jemoji
- jekyll-redirect-from
markdown: kramdown
permalink: pretty
exclude: ["node_modules", "Rakefile"]
footer: Version 1 by Victor Lourng. All images are public domain.
